spring:
  datasource:
    url: jdbc:mysql://121.169.203.219:3306/imos
    username: epin
    password: epin
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: imos-back-end

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

jwt:
  secret: your_jwt_secret_key_should_be_very_long_and_secure_at_least_256_bits
  token-validity-in-milliseconds: 86400000

server:
  port: 8080

# ?? ?? ??
logging:
  level:
    root: INFO
    kr.co.imoscloud: DEBUG
    org.springframework: INFO
    org.springframework.security: INFO