spring:
  datasource:
    url: jdbc:mysql://121.169.203.219:3306/imos
    username: epin
    password: epin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

  data:
    mongodb:
      uri: mongodb://121.169.203.219:37017/pb_sensor_data

  application:
    name: imos-back-end

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        # SQL 로깅 비활성화 (p6spy에서 담당)
        show_sql: false
        format_sql: false
        use_sql_comments: false
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false

  jackson:
      time-zone: Asia/Seoul



jwt:
  secret: your_jwt_secret_key_should_be_very_long_and_secure_at_least_256_bits
  token-validity-in-milliseconds: 86400000

server:
  port: 8080

# 로깅 설정
logging:
  level:
    root: INFO
    kr.co.imoscloud: DEBUG
    org.springframework: INFO
    org.springframework.security: INFO
    # Hibernate 로깅 비활성화 (p6spy에서 담당)
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    # p6spy 로그 레벨 설정
    p6spy: INFO

# p6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j