name: Build and Push Docker Image and deploy

on:
  push:
    branches:
      - main

concurrency:
  group: backend-deploy
  cancel-in-progress: true

jobs:
  java_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t 8pin/imos:springboot -f Dockerfile .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Push Docker image
      run: |
        docker push 8pin/imos:springboot

  deploy:
    runs-on: [self-hosted, terbotForAWS]
    needs:
      - java_build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into server and execute commands
        run: |
          echo "${{ secrets.KEY }}" > my_ec2_key.pem
          chmod 600 my_ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i my_ec2_key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
    
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PWD }}
          docker stop springboot || true
          docker rm springboot || true
          docker pull 8pin/imos:springboot
          
          docker run -d \
            --name springboot \
            --network imosNetwork \
            -p 8080:8080 \
            8pin/imos:springboot
          docker system prune -a -f
          EOF